markdown: kramdown
title: "CoilSnake"
latest_version: "4.2"
windows_download_url: "https://github.com/pk-hack/CoilSnake/releases/tag/v4.2"
social_media_links:
  twitter: https://twitter.com/
  github: https://github.com/pk-hack/CoilSnake
  
